services:
  db:
    image: postgres:19beta3
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: postgres19_graph_db
    ports:
      - "5434:5432" # host_port:container_port
